// svelte/src/components/Head.svelte
<script>
	import {link} from 'svelte-spa-router'
</script>

<header class="">
  <div class="container">
    <span><a href="/" use:link>[ Home ]</a>
    </span>
    <span><a href="/about" use:link>[ about ]</a>
    </span>
    <span><a href="/test1" use:link>[ Test1 ]</a>
    </span>
  </div>
  <hr />
</header>

<!--
-->

// react_ex_auth/src/components/Head.tsx
//import { Routes, Route, Link } from 'react-router-dom';
import {Link } from 'react-router-dom';
//
function Page() {
    return (
    <div>
        <a href="/" className="font-bold ms-4" > Home </a>
        <a href="/about" className="ms-2 text-gray-400"> [ about ]</a>
    </div>
    );
}
export default Page;
/*
*/
