// react_example/src/components/Head.tsx
//import { Routes, Route, Link } from 'react-router-dom';
import {Link } from 'react-router-dom';
//
function Page() {
    return (
    <div>
        <a href="/" className="font-bold ms-4" > Home </a>
        <a href="/about" className="ms-2 text-gray-400"> [ about ]</a>
        <a href="/todo11" className="font-bold ms-4" > todo11 </a>
        <a href="/todo13" className="font-bold ms-4" > todo13 </a>
        <a href="/todo24" className="font-bold ms-4" > todo24 </a>
    </div>
    );
}
export default Page;
/*
*/

// svelte5/src/components/Head.svelte
<script>
	import {link} from 'svelte-spa-router'
</script>

<header class="">
  <div class="container">
    <span><a href="/" use:link>[ Home ]</a>
    </span>
    <span><a href="/about" use:link>[ about ]</a>
    </span>
    <span><a href="/todo11" use:link>[ todo11 ]</a>
    </span>
    <span><a href="/todo13" use:link>[ todo13 ]</a>
    </span>
  </div>
  <hr />
</header>

<!--
-->
