// vue_example/src/App.vue
<script setup lang="ts">
//import HelloWorld from './components/HelloWorld.vue'
import { RouterLink } from 'vue-router';
//import Header from './components/Header.vue'
//
const pages = import.meta.glob('./client/*.vue', { eager: true })
const routes = Object.keys(pages).map((path) => {
  const name = path.match(/\.\/client\/(.*)\.vue$/)[1]
  return {
    name,
    path: name === 'Home' ? '/' : `/${name.toLowerCase()}`,
    component: pages[path].default,
  }
})
console.log("#App.vue");
//console.log(routes);
let items = routes;
</script>

<template>
  <div>
    <li v-for="item in items" :key="item.path">
      <router-link :to="'' + item.path">{{item.name}}</router-link>
    </li>
    <hr />
    <router-view></router-view>
  </div>
</template>

<style scoped>
</style>

// svelte_example/src/App.svelte
<script lang="ts">
import Router from 'svelte-spa-router'
//
import Head from './components/Head.svelte'
import LibLayout from './client/lib/LibLayout';
  //
  const pages = import.meta.glob('./client/*.svelte', { eager: true })
  
  const routes = Object.keys(pages).map((path) => {
    const name = path.match(/\.\/client\/(.*)\.svelte$/)[1]
    return {
      name,
      path: name === 'Home' ? '/' : `/${name.toLowerCase()}`,
      component: pages[path].default,
    }
  })
  export let routeArray = {};
  routes.forEach((item, idx) => {
    //console.log(item)
    let path = item.path;
    let compo = item.component;
    routeArray[item.path] = compo;
  });
LibLayout.startProc();
</script>


<!-- -->
<main>
    <hr />
    <Router routes={routeArray} />
    <hr />
</main>

<style>
</style>
<!--
<nav>
{#each routes as item}
<div>
  <a href={`/#${item.path}`}>{item.name}</a>
</div>
{/each}	
</nav>
-->
