// vue_example/src/client/Todo21/TodoDialog.vue
<template>
  <div v-if="isOpen" class="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center">
      <div class="bg-white p-6 rounded shadow-lg w-96">
          <h2 class="text-lg font-bold mb-4">{{ todo ? 'Edit TODO' : 'Add TODO' }}</h2>
           <div class="mb-4">
              <label for="title" class="block text-gray-700 text-sm font-bold mb-2">Title</label>
              <input type="text" id="title" v-model="editedTodo.title" class="border border-gray-300 rounded w-full px-3 py-2 focus:outline-none focus:border-blue-500" placeholder="Todo Title" />
           </div>
          <div v-if="todo" class="mb-4">
              <label for="completed" class="block text-gray-700 text-sm font-bold mb-2">Completed</label>
               <input type="checkbox" id="completed" v-model="editedTodo.completed" class="mr-2" />
           </div>
          <div class="flex justify-end">
              <button @click="close" class="bg-gray-400 hover:bg-gray-500 text-white font-bold py-2 px-4 rounded mr-2">
                  Cancel
              </button>
              <button @click="save" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
                  Save
              </button>
          </div>
      </div>
  </div>
</template>

<script>
import { watch } from 'vue';

export default {
  props: {
    isOpen: {
      type: Boolean,
      required: true,
    },
      todo: {
          type: Object,
          default: null
      },
  },
  data() {
    return {
      editedTodo: {
          title: '',
          completed: false,
      },
    };
  },
    watch: {
      todo: {
          handler(newTodo) {
            this.editedTodo = newTodo ? { ...newTodo } : { title: '', completed: false };
          },
          immediate: true
      },
    },
  methods: {
      close() {
          this.$emit('close');
      },
      save() {
          this.$emit('save', this.editedTodo);
      },
  },
};
</script>

// svelte5/src/client/Todo11/TodoDialog.svelte
<script lang="ts">
  import { todoSchema, type Todo } from './types';
  import { createEventDispatcher } from 'svelte';
  import { z } from 'zod';

  export let isOpen = false;
  export let todo: Partial<Todo> = { title: '', description: '', completed: false };
  export let mode: 'create' | 'edit' = 'create';

  const dispatch = createEventDispatcher();
  let errors: { [key: string]: string } = {};

  function handleSubmit() {
    try {
      const validatedTodo = todoSchema.parse(todo);
      dispatch('submit', validatedTodo);
      isOpen = false;
      errors = {};
    } catch (error) {
      console.log(error);
      if (error instanceof z.ZodError) {
        errors = error.errors.reduce((acc, curr) => {
          const field = curr.path[0];
          acc[field] = curr.message;
          return acc;
        }, {});
      }
    }
  }

  function handleClose() {
    isOpen = false;
    errors = {};
    dispatch('close');
  }
</script>

{#if isOpen}
<div class="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center">
  <div class="bg-white rounded-lg p-6 w-full max-w-md">
    <h2 class="text-xl font-bold mb-4">
      {mode === 'create' ? 'TODO追加' : 'TODO編集'}
    </h2>
    
    <form on:submit|preventDefault={handleSubmit} class="space-y-4">
      <div>
        <label class="block text-sm font-medium text-gray-700">タイトル</label>
        <input
          type="text"
          bind:value={todo.title}
          class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-blue-500 focus:ring-blue-500"
        />
        {#if errors.title}
          <p class="text-red-500 text-sm mt-1">{errors.title}</p>
        {/if}
      </div>

      <div>
        <label class="block text-sm font-medium text-gray-700">詳細</label>
        <textarea
          bind:value={todo.description}
          class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-blue-500 focus:ring-blue-500"
          rows="3"
        ></textarea>
      </div>

      <div class="flex items-center">
        <input
          type="checkbox"
          bind:checked={todo.completed}
          class="rounded border-gray-300 text-blue-600 focus:ring-blue-500"
        />
        <label class="ml-2 text-sm text-gray-700">完了</label>
      </div>

      <div class="flex justify-end space-x-3">
        <button
          type="button"
          on:click={handleClose}
          class="px-4 py-2 text-sm font-medium text-gray-700 bg-white border border-gray-300 rounded-md hover:bg-gray-50"
        >
          キャンセル
        </button>
        <button
          type="submit"
          class="px-4 py-2 text-sm font-medium text-white bg-blue-600 border border-transparent rounded-md hover:bg-blue-700"
        >
          {mode === 'create' ? '追加' : '更新'}
        </button>
      </div>
    </form>
  </div>
</div>
{/if}
