// svelte_example/src/client/Todo11.svelte

<script lang="ts">
  import { onMount } from 'svelte';
  import Head from "../components/Head.svelte";
  import TodoDialog from './Todo11/TodoDialog.svelte';
  import type { Todo } from './Todo11/types';
  import * as api from './Todo11/api';

  let todos: (Todo & { id: number })[] = [];
  let isDialogOpen = false;
  let currentTodo: Partial<Todo> = {};
  let dialogMode: 'create' | 'edit' = 'create';
  let searchQuery = '';
  let loading = true;
  let error: string | null = null;

  onMount(async () => {
    try {
      todos = await api.fetchTodos();
    } catch (e) {
      error = 'TODOの取得に失敗しました';
    } finally {
      loading = false;
    }
  });

  async function handleSearch() {
    if (!searchQuery.trim()) {
      todos = await api.fetchTodos();
      return;
    }
    todos = await api.searchTodos(searchQuery);
  }

  async function handleSubmit(event: CustomEvent<Todo>) {
    try {
      if (dialogMode === 'create') {
        const newTodo = await api.createTodo(event.detail);
        console.log(newTodo);
        todos = [newTodo, ...todos];
      } else {
        const updatedTodo = await api.updateTodo(currentTodo.id!, event.detail);
        todos = todos.map(todo => 
          todo.id === currentTodo.id ? updatedTodo : todo
        );
      }
    } catch (e) {
      console.error(e);
      error = dialogMode === 'create' ? 
        'TODOの作成に失敗しました' : 
        'TODOの更新に失敗しました';
    }
  }

  async function handleDelete(id: number) {
    if (!confirm('本当に削除しますか？')) return;
    try {
      await api.deleteTodo(id);
      todos = todos.filter(todo => todo.id !== id);
    } catch (e) {
      error = 'TODOの削除に失敗しました';
    }
  }

  function openCreateDialog() {
    dialogMode = 'create';
    currentTodo = { title: '', description: '', completed: false };
    isDialogOpen = true;
  }

  function openEditDialog(todo: Todo & { id: number }) {
    dialogMode = 'edit';
    currentTodo = { ...todo };
    isDialogOpen = true;
  }
</script>

<Head />
<div class="container mx-auto px-4 py-8">
  <h1 class="text-3xl font-bold mb-8">TODOリスト</h1>

  {#if error}
    <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded mb-4">
      {error}
    </div>
  {/if}

  <div class="flex justify-between items-center mb-6">
    <div class="flex-1 max-w-sm mr-4">
      <input
        type="text"
        bind:value={searchQuery}
        on:input={() => handleSearch()}
        placeholder="検索..."
        class="w-full px-4 py-2 rounded-md border border-gray-300"
      />
    </div>
    <button
      on:click={openCreateDialog}
      class="px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700"
    >
      新規追加
    </button>
  </div>

  {#if loading}
    <div class="text-center py-8">
      <div class="animate-spin rounded-full h-8 w-8 border-b-2 border-gray-900 mx-auto"></div>
    </div>
  {:else}
    <div class="space-y-4">
      {#each todos as todo (todo.id)}
        <div class="flex items-center justify-between p-4 bg-white rounded-lg shadow">
          <div class="flex items-center flex-1">
            <input
              type="checkbox"
              checked={todo.completed}
              on:change={() => openEditDialog({ ...todo, completed: !todo.completed })}
              class="h-4 w-4 rounded border-gray-300 text-blue-600"
            />
            <div class="ml-4">
              <h3 class="text-lg font-medium {todo.completed ? 'line-through text-gray-500' : ''}">{todo.title}</h3>
              {#if todo.description}
                <p class="text-gray-600 mt-1">{todo.description}</p>
              {/if}
            </div>
          </div>
          <div class="flex space-x-2">
            <button
              on:click={() => openEditDialog(todo)}
              class="px-3 py-1 text-sm text-blue-600 hover:bg-blue-50 rounded"
            >
              編集
            </button>
            <button
              on:click={() => handleDelete(todo.id)}
              class="px-3 py-1 text-sm text-red-600 hover:bg-red-50 rounded"
            >
              削除
            </button>
          </div>
        </div>
      {/each}
    </div>
  {/if}
</div>

<TodoDialog
  bind:isOpen={isDialogOpen}
  bind:todo={currentTodo}
  mode={dialogMode}
  on:submit={handleSubmit}
/>

// react_example/src/client/todo11.tsx
import React, { useState, useEffect } from 'react';
import axios from 'axios';
import { z } from 'zod';
import  Head from "../components/Head";

// Zod バリデーションスキーマ
const todoSchema = z.object({
  title: z.string().min(1, { message: 'タイトルは必須です' }),
});

let API_URL=""
async function getSysApiUrl(){
  try{
    let ret = "";
    const response = await fetch(`/api/common/get_sys_items`,
      {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({}),
      }
    );
    if (!response.ok) throw new Error("error, getSystemParam");
    const data = await response.json();
    //console.log(data.data);
    ret = data.data.api_url;
    return ret;
  } catch (err) {
    console.error(err);
  }
}

function App() {
  const [todos, setTodos] = useState([]);
  const [isAddModalOpen, setIsAddModalOpen] = useState(false);
  const [isEditModalOpen, setIsEditModalOpen] = useState(false);
  const [editingTodo, setEditingTodo] = useState(null);
  const [searchQuery, setSearchQuery] = useState('');
  const [errors, setErrors] = useState({});

  // TODOの取得
  useEffect(() => {
    const fetchTodos = async () => {
      try {
        //API_URL = await getSysApiUrl();
        //console.log("apiUrl=", API_URL)
        const response = await axios.get(`${API_URL}/api/todo14?q=${searchQuery}`);
        console.log(response.data);
        setTodos(response.data.results);
      } catch (error) {
        console.error('Error fetching todos:', error);
      }
    };
    fetchTodos();
  }, [searchQuery]);

  // TODOの追加
  const handleAddTodo = async (newTodo) => {
    try {
      // バリデーション
      todoSchema.parse(newTodo);
      setErrors({});
  
      const response = await axios.post(API_URL + '/api/todo14', newTodo);
      setTodos([...todos, response.data]);
      setIsAddModalOpen(false);
    } catch (error) {
      if (error instanceof z.ZodError) {
        const newErrors = {};
        error.errors.forEach(err => {
          newErrors[err.path[0]] = err.message;
        });
        setErrors(newErrors);
      } else {
        console.error('Error adding todo:', error);
      }
    }
  };

  // TODOの更新
  const handleUpdateTodo = async (updatedTodo) => {
    try {
      // バリデーション
      todoSchema.parse(updatedTodo);
      setErrors({});
  
      const response = await axios.put(`${API_URL}/api/todo14/${updatedTodo.id}`, updatedTodo);
      setTodos(todos.map(todo => todo.id === updatedTodo.id ? response.data : todo));
      setIsEditModalOpen(false);
      setEditingTodo(null);
    } catch (error) {
      if (error instanceof z.ZodError) {
        const newErrors = {};
        error.errors.forEach(err => {
          newErrors[err.path[0]] = err.message;
        });
        setErrors(newErrors);
      } else {
        console.error('Error updating todo:', error);
      }
    }
  };

  // TODOの削除
  const handleDeleteTodo = async (id) => {
    try {
      await axios.delete(`${API_URL}/api/todo14/${id}`);
      setTodos(todos.filter(todo => todo.id !== id));
    } catch (error) {
      console.error('Error deleting todo:', error);
    }
  };

  // ダイアログを開く（追加）
  const openAddModal = () => {
    setIsAddModalOpen(true);
    setErrors({});
  };

  // ダイアログを閉じる（追加）
  const closeAddModal = () => {
    setIsAddModalOpen(false);
    setErrors({});
  };

  // ダイアログを開く（編集）
  const openEditModal = (todo) => {
    setEditingTodo(todo);
    setIsEditModalOpen(true);
    setErrors({});
  };

  // ダイアログを閉じる（編集）
  const closeEditModal = () => {
    setIsEditModalOpen(false);
    setEditingTodo(null);
    setErrors({});
  };

  return (
  <>
    <Head />
    <div className="container mx-auto p-4">
      <h1 className="text-2xl font-bold mb-4">Todo11</h1>

      {/* 検索バー */}
      <div className="mb-4">
        <input
          type="text"
          placeholder="TODOを検索..."
          value={searchQuery}
          onChange={(e) => setSearchQuery(e.target.value)}
          className="border border-gray-300 px-3 py-2 rounded w-full"
        />
      </div>

      {/* 追加ボタン */}
      <button onClick={openAddModal} className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded mb-4">
        TODOを追加
      </button>

      {/* TODOリスト */}
      <ul>
        {todos.map(todo => (
          <li key={todo.id} className="flex items-center justify-between border-b border-gray-300 py-2">
            <span className={todo.completed ? 'line-through text-gray-500' : ''}>
              {todo.title}
            </span>
            <div>
              <button onClick={() => openEditModal(todo)} className="bg-yellow-500 hover:bg-yellow-700 text-white font-bold py-1 px-2 rounded mr-2">
                編集
              </button>
              <button onClick={() => handleDeleteTodo(todo.id)} className="bg-red-500 hover:bg-red-700 text-white font-bold py-1 px-2 rounded">
                削除
              </button>
            </div>
          </li>
        ))}
      </ul>

      {/* 追加ダイアログ */}
      {isAddModalOpen && (
        <div id="dialog" class="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center">
          <div class="bg-white rounded-lg shadow-lg p-6 max-w-md w-full">
            <h2 className="text-xl font-bold mb-4">TODOを追加</h2>
            <AddTodoForm onAddTodo={handleAddTodo} onClose={closeAddModal} errors={errors} />
          </div>
        </div>
      )}

      {/* 編集ダイアログ */}
      {isEditModalOpen && editingTodo && (
        <div id="dialog" class="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center">
          <div className="bg-white rounded-lg shadow-lg p-6 max-w-md w-full">
            <h2 className="text-xl font-bold mb-4">TODOを編集</h2>
            <EditTodoForm todo={editingTodo} onUpdateTodo={handleUpdateTodo} onClose={closeEditModal} errors={errors} />
          </div>
        </div>
      )}
    </div>  
  </>

  );
}

// 追加フォームコンポーネント
function AddTodoForm({ onAddTodo, onClose, errors }) {
  const [title, setTitle] = useState('');

  const handleSubmit = (e) => {
    e.preventDefault();
    onAddTodo({ title });
    setTitle('');
  };

  return (
    <form onSubmit={handleSubmit}>
      <div className="mb-4">
        <label htmlFor="title" className="block mb-2">タイトル</label>
        <input
          type="text"
          id="title"
          value={title}
          onChange={(e) => setTitle(e.target.value)}
          className={`border border-gray-300 px-3 py-2 rounded w-full ${errors.title ? 'border-red-500' : ''}`}
        />
        {errors.title && <p className="text-red-500 text-sm mt-1">{errors.title}</p>}
      </div>
      <div className="flex justify-end">
        <button type="submit" className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded mr-2">
          追加
        </button>
        <button type="button" onClick={onClose} className="bg-gray-500 hover:bg-gray-700 text-white font-bold py-2 px-4 rounded">
          キャンセル
        </button>
      </div>
    </form>
  );
}

// 編集フォームコンポーネント
function EditTodoForm({ todo, onUpdateTodo, onClose, errors }) {
  const [title, setTitle] = useState(todo.title);
  const [completed, setCompleted] = useState(todo.completed);

  const handleSubmit = (e) => {
    e.preventDefault();
    onUpdateTodo({ ...todo, title, completed });
  };

  return (
    <form onSubmit={handleSubmit}>
      <div className="mb-4">
        <label htmlFor="title" className="block mb-2">タイトル</label>
        <input
          type="text"
          id="title"
          value={title}
          onChange={(e) => setTitle(e.target.value)}
          className={`border border-gray-300 px-3 py-2 rounded w-full ${errors.title ? 'border-red-500' : ''}`}
        />
        {errors.title && <p className="text-red-500 text-sm mt-1">{errors.title}</p>}
      </div>
      <div className="mb-4">
        <label htmlFor="completed" className="block mb-2">
          <input
            type="checkbox"
            id="completed"
            checked={completed}
            onChange={(e) => setCompleted(e.target.checked)}
            className="mr-2"
          />
          完了
        </label>
      </div>
      <div className="flex justify-end">
        <button type="submit" className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded mr-2">
          更新
        </button>
        <button type="button" onClick={onClose} className="bg-gray-500 hover:bg-gray-700 text-white font-bold py-2 px-4 rounded">
          キャンセル
        </button>
      </div>
    </form>
  );
}

export default App;
